version: '3.8'

services:
  ecom-postgres:
    image: postgres:latest
    container_name: ecom-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ecom
    ports:
      - "5432:5432"

  ecom:
    build: .
    container_name: ecom
    ports:
      - "8080:8080"
    depends_on:
      - ecom-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ecom-postgres:5432/ecom
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
